# Central configuration for inputs and outputs

inputs:
  orders_input:
    path: input_folder/orders.csv
    file_schema: # Renamed 'schema' to 'file_schema'
      name: OrdersSchema
      columns:
        order_id: { type: integer }
        customer_id: { type: integer }
        order_date: { type: string } # Will be cast in pipelines
        product_name: { type: string }
        quantity: { type: integer }
        unit_price: { type: string } # Will be cleaned and cast in pipelines

  customers_input:
    path: input_folder/customers.csv
    file_schema: # Renamed 'schema' to 'file_schema'
      name: CustomersSchema
      columns:
        customer_id: { type: integer }
        customer_name: { type: string }
        city: { type: string }
        country: { type: string }
        signup_date: { type: string } # Will be cast in pipelines

  products_input:
    path: input_folder/products.csv
    file_schema: # Renamed 'schema' to 'file_schema'
      name: ProductsSchema
      columns:
        product_name: { type: string }
        category: { type: string }
        cost_price: { type: string } # Will be cast in pipelines

outputs:
  enriched_output_def:
    path: output_folder/enriched_orders_final.csv
    format: csv
    file_schema:
      name: EnrichedSchema
      columns:
        order_id: { type: integer , description : "id of the order"}
        customer_id: { type: integer }
        order_date_dt: { type: date }
        product_name: { type: string }
        quantity: { type: integer , description : "number of items"}
        unit_price_float: { type: float }
        total_price: { type: float , description : "unit price time the number of items"}
        customer_name: { type: string }
        city: { type: string , description : "city of customer"}
        country: { type: string , description : "coutry of customer" }
        signup_date_dt: { type: date }
        category: { type: string }
        cost_price_float: { type: float }
        total_cost: { type: float }
        profit: { type: float , description : "price - cost"}
        is_high_profit: { type: boolean, description : "if more that %100 profit on the product"}
        order_status: { type: string }


  summary_output_def:
    path: output_folder/profit_by_region_category.csv
    format: csv
    file_schema:
      name: SummarySchema
      columns:
        customer_region: { type: string }
        product_name : { type: string }
        Electronics: { type: float , description : "profit if it's the category of the item, else 0"}
        Furniture: { type: float , description : "profit if it's the category of the item, else 0" }
        Stationery: { type: float , description : "profit if it's the category of the item, else 0"}
        other_column : { type: float , description : "profit if it's the category of the item, else 0"}
